#!/bin/bash


source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate slak


python run_with_submitit.py --nodes 2 --ngpus 4 --model convnext_small_Rep --drop_path 0.4 --timeout 1 \
--batch_size 64 --lr 4e-3 --update_freq 8 --model_ema true --model_ema_eval true \
--data_path /projects/2/managed_datasets/imagenet/ --num_workers 72 --kernel-size 51 49 47 13 3 \
--job_dir /projects/0/prjste21060/projects/SLaK/checkpoint/small/milti_node



source deactivate
