#!/bin/bash
#SBATCH --job-name=slak_5x5
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --gpus=4
#SBATCH -t 2-23:59:59
#SBATCH --exclusive
#SBATCH --cpus-per-task=72
#SBATCH -o slak_5x5.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

#module purge
#module load 2021
#module load CUDA/11.3.1
#module load PyTorch/1.10.0-foss-2021a-CUDA-11.3.1


model=convnext_tiny_Rep
python -m torch.distributed.launch --nproc_per_node=4 main.py  \
--width-factor 1.0 -u 2000 --init-density 0.6 --method DST --sparse-init snip  --prune-rate 0.5 \
--epochs 120 --model $model --drop_path 0.1 --batch_size 128 --lr 4e-3 --update_freq 8 --model_ema true \
--model_ema_eval true --data_path /projects/2/managed_datasets/imagenet/ --num_workers 72 --kernel-size 5 5 5 5 100 \
--output_dir /projects/0/prjste21060/projects/LoRA_LK/transfer/$model/5555/120epochs/



source deactivate
